<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Michael Kerr">
  <meta name="dcterms.date" content="2025-12-04">
  <title>When TDA Works: Combining Topological and Traditional Features for Karst Classification</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link href="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
<script src="mathjax-config.js"></script>
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">When TDA Works: Combining Topological and Traditional Features for Karst Classification</h1>
  <p class="subtitle">GEOG 6591: Introduction to Geospatial Artificial Intelligence</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Michael Kerr 
</div>
        <p class="quarto-title-affiliation">
            Course Instructor: Dr.&nbsp;Weiming Hu | Math DRP Advisor: Cameron Thomas, PhD Candidate
          </p>
    </div>
</div>

  <p class="date">December 4, 2025</p>
</section>
<section class="slide level2">

<style>
/* Right-align tikz figures in revealjs */
.reveal .slides section .quarto-figure-right,
.reveal .slides section figure.quarto-figure-right,
.reveal .slides section img.quarto-figure-right,
.reveal .slides section svg.quarto-figure-right,
.reveal .slides section .tikz-right,
.reveal .slides section figure.tikz-right,
.reveal .slides section img.tikz-right,
.reveal .slides section svg.tikz-right {
  margin-left: auto !important;
  margin-right: 0 !important;
  display: block;
  width: auto;
}

/* Target tikz figures in list items (more specific) */
.reveal .slides section ul li figure.tikz-right,
.reveal .slides section ul li img.tikz-right,
.reveal .slides section ul li svg.tikz-right,
.reveal .slides section ul li .tikz-right {
  margin-left: auto !important;
  margin-right: 0 !important;
  display: block;
  width: auto;
}
</style>
</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<ul>
<li><strong>The Problem</strong>: Automated terrain classification challenge</li>
<li><strong>Study Area &amp; Data</strong>: Warren/Hardin Counties, Kentucky (Mammoth Cave region)</li>
<li><strong>Four Competing Approaches</strong>: Traditional, TDA, Deep Learning, Hybrid</li>
<li><strong>Topology Overview</strong>: TDA in simple terms</li>
<li><strong>Experimental Design</strong>: Random vs Spatial cross-validation</li>
<li><strong>Results</strong>: Performance, efficiency, and practical impact</li>
<li><strong>Interpretation</strong>: What worked and practical recommendations</li>
</ul>
</section>
<section>
<section id="the-problem" class="title-slide slide level1 center">
<h1>The Problem</h1>

</section>
<section id="research-question" class="slide level2">
<h2>Research Question</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Research Question</strong></p>
</div>
<div class="callout-content">
<p>Can Topological Data Analysis (TDA) enhance traditional geomorphology metrics for classifying surficial geology from Digital Elevation Models (DEMs) while improving computational efficiency?</p>
</div>
</div>
</div>
<aside class="notes">
<p>Traditional geomorphometry requires expert interpretation of slope, curvature, and drainage patterns. TDA offers coordinate-free shape descriptors. Do they capture karst morphology effectively?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-challenge-why-karst-matters" class="slide level2">
<h2>The Challenge &amp; Why Karst Matters</h2>
<p><strong>Challenge:</strong></p>
<ul>
<li>Expensive field surveys</li>
<li>Time-consuming manual interpretation</li>
<li>Expert knowledge and resources</li>
</ul>
<p><strong>Why karst matters:</strong></p>
<ul>
<li>Karst aquifers provide 25% of global drinking water</li>
<li>Sinkholes cause $300M+ annual infrastructure damage in US</li>
<li>Climate change accelerates karst evolution</li>
</ul>
<aside class="notes">
<p>Traditional surficial geology mapping requires expensive field surveys, time-consuming manual interpretation, and expert knowledge. Climate change accelerates karst evolution, making automated monitoring increasingly necessary.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="opportunity-hypothesis" class="slide level2">
<h2>Opportunity &amp; Hypothesis</h2>
<ul>
<li>Groundwater management and aquifer protection</li>
<li>Hazard assessment (sinkhole risk mapping)</li>
<li>Land use planning and infrastructure development</li>
<li>Large-scale automated monitoring</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hypothesis vs.&nbsp;Finding</strong></p>
</div>
<div class="callout-content">
<p><strong>Hypothesis:</strong> TDA can replace expensive multi-scale geomorphometry.</p>
<p><strong>Finding:</strong> It cannot replace expensive multi-scale geomorphometry, but combining them gives best results.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Automated classification from DEMs could enable groundwater management, support hazard assessment, inform land use planning, and enable large-scale automated monitoring. This study compares four computational approaches to find the best method. We’ll explore why combining TDA with traditional methods works best.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="study-area-dataset" class="title-slide slide level1 center">
<h1>Study Area &amp; Dataset</h1>

</section>
<section id="study-area-warren-hardin-counties-kentucky" class="slide level2">
<h2>Study Area: Warren &amp; Hardin Counties, Kentucky</h2>
<div style="text-align: center;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/study_area_map.png" style="width:80.0%"></p>
<figcaption>Study Area Map</figcaption>
</figure>
</div>
<p><strong>Mammoth Cave National Park Region</strong></p>
</div>
<aside class="notes">
<p>This region is ideal for karst terrain classification. The Kentucky sinkhole plain is a type locality for covered karst, with 1000+ sinkholes per km² in some areas and complex interaction of surface/subsurface drainage. High-quality 1m LiDAR DEMs capture micro-topography, and surficial geology is well-documented by USGS and state geological survey. The topologically complex terrain is ideal for testing TDA’s shape-capture ability.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dataset-earthscape-multi-label-classification" class="slide level2">
<h2>Dataset: EarthScape Multi-label Classification</h2>
<ul>
<li><strong>30,643 DEM tiles</strong> (256×256 pixels each)</li>
<li><strong>7 surficial geology classes:</strong>
<ul>
<li>af1: Artificial Fill</li>
<li>Qal: Alluvium</li>
<li>Qaf: Alluvial Fans</li>
<li>Qat: Alluvial Terraces</li>
<li>Qc: Colluvium</li>
<li>Qca: Colluvial Accumulations</li>
<li>Qr: Residuum</li>
</ul></li>
</ul>

<img data-src="../../../outputs/presentation_visuals/class_distribution.png" style="width:80.0%" class="r-stretch quarto-figure-center"><p class="caption">Class Distribution</p><aside class="notes">
<p>This is a multi-label classification problem. Tiles can have multiple classes simultaneously, for example Qal (Alluvium) combined with Qc (Colluvium).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="four-competing-approaches" class="title-slide slide level1 center">
<h1>Four Competing Approaches</h1>

</section>
<section id="four-computational-approaches" class="slide level2">
<h2>Four Computational Approaches</h2>

<img data-src="../../../outputs/presentation_visuals/four_approaches.png" style="width:90.0%" class="r-stretch quarto-figure-center"><p class="caption">Four Approaches Overview</p><p><strong>Goal:</strong></p>
<ul>
<li>Predictive accuracy (F1-macro score)</li>
<li>Computational efficiency (time per tile)</li>
<li>Interpretability</li>
</ul>
<aside class="notes">
<p>We aim to determine which approach provides the best balance of predictive accuracy, computational efficiency, and interpretability. Understanding what features matter is crucial for practical applications.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deep-learning-inputs-what-the-models-see" class="slide level2">
<h2>Deep Learning Inputs: What the Models See</h2>
<p><strong>Arena 1 (Geometry):</strong> 3-channel input from DEM derivatives</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/vision_inputs_geometry.png" style="width:90.0%"></p>
<figcaption>Geometry Inputs</figcaption>
</figure>
</div>
<p><strong>Arena 2 (RGB):</strong> Aerial imagery from EarthScape dataset</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/vision_inputs_rgb.png" style="width:90.0%"></p>
<figcaption>RGB Inputs</figcaption>
</figure>
</div>
</section></section>
<section>
<section id="topology-overview" class="title-slide slide level1 center">
<h1>Topology Overview</h1>

</section>
<section id="topological-data-analysis-tda" class="slide level2">
<h2>Topological Data Analysis (TDA)</h2>
<p><strong>TDA tracks how topological features like sinkholes and ridges appear and disappear as we filter terrain by elevation threshold.</strong></p>
<div style="text-align: center;">
<p><img data-src="../../../outputs/presentation_visuals/filtration_frames/filtration_frame_01.png" class="fragment" style="width:80.0%" data-fragment-index="0"></p>
<p><img data-src="../../../outputs/presentation_visuals/filtration_frames/filtration_frame_03.png" class="fragment" style="width:80.0%" data-fragment-index="1"></p>
<p><img data-src="../../../outputs/presentation_visuals/filtration_frames/filtration_frame_05.png" class="fragment" style="width:80.0%" data-fragment-index="2"></p>
<p><img data-src="../../../outputs/presentation_visuals/filtration_frames/filtration_frame_07.png" class="fragment" style="width:80.0%" data-fragment-index="3"></p>
</div>
<aside class="notes">
<p>Sinkholes are topological holes, and ridges are peaks. Long-lasting features are geologically significant, while transient features are noise.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-three-filtrations" class="slide level2">
<h2>Why Three Filtrations?</h2>
<ul>
<li><strong>Elevation:</strong> valleys and depressions</li>
<li><strong>Slope:</strong> steep areas and terrain steepness patterns<br>
</li>
<li><strong>Superlevel:</strong> peaks and ridges</li>
</ul>
<aside class="notes">
<p>Different filtrations capture different morphology. Elevation captures valleys and depressions, slope captures steep areas and terrain steepness patterns, and superlevel captures peaks and ridges.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<p><img data-src="../../../outputs/presentation_visuals/filtration_comparison_elevation.png" style="width:30.0%" alt="Elevation Filtration"> <img data-src="../../../outputs/presentation_visuals/filtration_comparison_slope.png" style="width:30.0%" alt="Slope Filtration"> <img data-src="../../../outputs/presentation_visuals/filtration_comparison_superlevel.png" style="width:30.0%" alt="Superlevel Filtration"></p>
</section></section>
<section>
<section id="detailed-tda-formalism" class="title-slide slide level1 center">
<h1>Detailed TDA Formalism</h1>

</section>
<section id="simplicial-complexes-building-blocks-of-topology" class="slide level2">
<h2>Simplicial Complexes: Building Blocks of Topology</h2>
<p><strong>Definition:</strong> An abstract simplicial complex <span class="math inline">\(K\)</span> is a collection of subsets of vertices closed under subsets (<span class="math inline">\(\sigma \in K, \tau \subseteq \sigma \implies \tau \in K\)</span>).</p>
<p><strong>Basis Elements:</strong> A <span class="math inline">\(k\)</span>-simplex is a subset with <span class="math inline">\(k+1\)</span> vertices.</p>
<ul>
<li><p><strong>0-Simplex</strong>: <span class="math inline">\(\{v_0\}\)</span> (Vertex)</p>
<img data-src="presentation_files\mediabag\3e9ab44ecca0ecf0863a639c026d57d97c2106a2.svg" data-classes="tikz-right" data-eval="false" data-echo="false"></li>
<li><p><strong>1-Simplex</strong>: <span class="math inline">\(\{v_0, v_1\}\)</span> (Edge)</p>
<img data-src="presentation_files\mediabag\1428b860afc3849a255ce0fb4d3e45b55fb74237.svg" data-classes="tikz-right" data-eval="false" data-echo="false"></li>
<li><p><strong>2-Simplex</strong>: <span class="math inline">\(\{v_0, v_1, v_2\}\)</span> (Face)</p>
<img data-src="presentation_files\mediabag\5f623852ff3d6e4bbd63f3356db219b4a4710693.svg" data-classes="tikz-right" data-eval="false" data-echo="false"></li>
</ul>
<p><strong>For terrain:</strong> Simplices represent how elevation points connect to form topological features (sinkholes, peaks, valleys).</p>
</section>
<section id="betti-numbers-counting-topological-features" class="slide level2">
<h2>Betti Numbers: Counting Topological Features</h2>
<p><strong>Betti numbers</strong> count <span class="math inline">\(k\)</span>-dimensional “holes” in the terrain:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: <strong>Connected components</strong> (separate landmasses)</li>
<li><span class="math inline">\(\beta_1\)</span>: <strong>1D loops</strong> (sinkholes, closed depressions)</li>
<li><span class="math inline">\(\beta_2\)</span>: <strong>2D voids</strong> (cavities, underground features)</li>
</ul>
<p><strong>Key property:</strong> Topological invariants are coordinate-free and deformation-invariant. They describe terrain <em>shape</em> regardless of how we measure it.</p>
</section>
<section id="persistent-homology-multi-scale-topology" class="slide level2">
<h2>Persistent Homology: Multi-Scale Topology</h2>
<p><strong>Filtration:</strong> A nested sequence of complexes <span class="math inline">\(\emptyset = K_0 \subseteq K_1 \subseteq \cdots \subseteq K_n\)</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sublevel Set Filtration</strong></p>
</div>
<div class="callout-content">
<p>Given elevation function <span class="math inline">\(f: X \to \mathbb{R}\)</span>, the sublevel set filtration is:</p>
<p><span class="math display">\[X_t = \{x \in X \mid f(x) \le t\}\]</span></p>
<p>As threshold <span class="math inline">\(t\)</span> increases, we track how topological features (sinkholes, peaks) appear and disappear.</p>
</div>
</div>
</div>
<p><strong>For terrain:</strong> Persistence measures how “significant” a feature is. Long-lasting features like deep sinkholes are more geologically important than transient ones.</p>
</section>
<section id="geometric-realizations-cubical-vs-simplicial-complexes" class="slide level2">
<h2>Geometric Realizations: Cubical vs Simplicial Complexes</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align: center;">
<p><strong>Simplicial Complex</strong></p>
<img data-src="presentation_files\mediabag\e272b991b20b28a6e1bac8359516009e21c0cf61.svg" data-eval="false" data-echo="false">
<ul>
<li>Requires triangulation</li>
<li>General-purpose</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<div style="text-align: center;">
<p><strong>Cubical Complex</strong></p>
<img data-src="presentation_files\mediabag\43d81b02c0503eb6de5ae5672ce155bfb0bf5d2f.svg" data-eval="false" data-echo="false">
<ul>
<li>Native to grid/DEM data</li>
<li>No artificial subdivision</li>
<li>More efficient for raster data</li>
</ul>
</div>
</div></div>
<p><strong>For DEMs:</strong> Cubical complexes avoid unnecessary triangulation, making TDA computations faster.</p>
</section>
<section id="vectorization-methods-for-machine-learning" class="slide level2">
<h2>Vectorization Methods for Machine Learning</h2>
<div style="text-align: center;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/256_50_11_feature_rosetta_stone.png" style="width:67.0%"></p>
<figcaption>Feature Rosetta Stone</figcaption>
</figure>
</div>
</div>
<aside class="notes">
<p>This visualization shows how different feature extraction methods represent the same terrain tile. It’s a “Rosetta Stone” connecting all feature representations back to a single piece of terrain, demonstrating the tradeoffs between different approaches.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="experimental-design" class="title-slide slide level1 center">
<h1>Experimental Design</h1>

</section>
<section id="the-spatial-autocorrelation-problem" class="slide level2">
<h2>The Spatial Autocorrelation Problem</h2>

<img data-src="../../../outputs/presentation_visuals/experimental_design.png" style="width:100.0%" class="r-stretch quarto-figure-center"><p class="caption">Experimental Design: Random vs Spatial CV</p><p><strong>Problem:</strong> Geospatial data has spatial autocorrelation. Nearby tiles are similar.</p>
<ul>
<li><strong>Random CV:</strong> mixes training and test tiles from same region</li>
<li><strong>Spatial CV:</strong> groups tiles by geological region</li>
</ul>
<aside class="notes">
<p>Random CV mixes training and test tiles from the same region, leading to inflated performance. Spatial CV groups tiles by geological region, providing honest generalization estimates. Random CV inflates performance by approximately 7 F1 points. Spatial CV provides realistic estimates for real-world deployment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="our-experimental-approach" class="slide level2">
<h2>Our Experimental Approach</h2>
<ul>
<li>Leave-One-Region-Out cross-validation (<code>GroupKFold</code>, 8 regions)</li>
<li>Random Forest (MultiOutputClassifier) with balanced class weights</li>
<li>F1-macro metric</li>
</ul>
<aside class="notes">
<p>We use Leave-One-Region-Out cross-validation with GroupKFold across 8 regions total. The classifier is Random Forest with MultiOutputClassifier wrapper and balanced class weights. F1-macro handles multi-label and imbalanced classification.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="results-random-cv-performance" class="title-slide slide level1 center">
<h1>Results: Random CV Performance</h1>

</section>
<section id="random-cv-top-performers" class="slide level2">
<h2>Random CV: Top Performers</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Rank</th>
<th>Method</th>
<th>Dimensions</th>
<th>F1-macro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Multi-scale + Texture</td>
<td>84d</td>
<td><strong>0.731</strong> ± 0.006</td>
</tr>
<tr class="even">
<td>2</td>
<td>Multi-scale + Texture + Betti</td>
<td>184d</td>
<td><strong>0.728</strong> ± 0.009</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Multi-scale + Betti</td>
<td>170d</td>
<td><strong>0.726</strong> ± 0.012</td>
</tr>
<tr class="even">
<td>4</td>
<td>Multi-scale Derivatives</td>
<td>70d</td>
<td><strong>0.725</strong> ± 0.008</td>
</tr>
<tr class="odd">
<td>5</td>
<td>ResNet-50 (Geometry)</td>
<td>2048d</td>
<td><strong>0.714</strong> ± 0.011</td>
</tr>
<tr class="even">
<td>6</td>
<td>Core Derivatives</td>
<td>30d</td>
<td><strong>0.712</strong> ± 0.009</td>
</tr>
<tr class="odd">
<td>7</td>
<td>ViT-Base (Geometry)</td>
<td>768d</td>
<td><strong>0.708</strong> ± 0.010</td>
</tr>
<tr class="even">
<td>8</td>
<td>Betti Curves</td>
<td>100d</td>
<td><strong>0.606</strong> ± 0.009</td>
</tr>
</tbody>
</table>
</section>
<section id="classification-results" class="slide level2">
<h2>Classification Results</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align: center;">
<p><strong>Computational Efficiency</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/timing_feasibility.png" style="width:100.0%"></p>
<figcaption>Timing Feasibility</figcaption>
</figure>
</div>
</div>
</div><div class="column" style="width:50%;">
<div style="text-align: center;">
<p><strong>Predictive Power</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../../outputs/presentation_visuals/performance_comparison.png" style="width:100.0%"></p>
<figcaption>Performance Comparison</figcaption>
</figure>
</div>
</div>
</div></div>
<aside class="notes">
<p>Side-by-side comparison of computational efficiency and predictive power. TDA alone underperforms traditional methods, but TDA plus Traditional combinations achieve best performance. The highest F1 score of 0.731 is not the ultra-robust method. The ultra-robust method (Multi-scale + Betti, 0.726) has the strongest statistical evidence of equivalence, though slightly lower F1.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="statistical-robustness-ultra-robust-methods" class="slide level2">
<h2>Statistical Robustness: Ultra-Robust Methods</h2>

<img data-src="../../../outputs/presentation_visuals/ultra_robust_methods.png" style="width:90.0%" class="r-stretch quarto-figure-center"><p class="caption">Ultra-Robust Methods</p><aside class="notes">
<p>Three methods show near-certainty with Bonferroni-corrected p less than 0.0002 in both CV types. P-values are 200 to 8,000 times below the ultra-conservative threshold. All three combine multiscale Betti curves with multiscale derivatives. This is our strongest scientific finding, demonstrating that topological features are most effective when integrated with traditional features at multiple scales.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="results-spatial-cv-geographic-reality" class="title-slide slide level1 center">
<h1>Results: Spatial CV (Geographic Reality)</h1>

</section>
<section id="spatial-cv-performance-drops-rankings-shift" class="slide level2">
<h2>Spatial CV: Performance Drops, Rankings Shift</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Rank</th>
<th>Method</th>
<th>Dimensions</th>
<th>F1-macro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Multi-scale + Betti</td>
<td>170d</td>
<td><strong>0.663</strong> ± 0.149</td>
</tr>
<tr class="even">
<td>2</td>
<td>Multi-scale + Texture + Betti</td>
<td>184d</td>
<td><strong>0.662</strong> ± 0.138</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Multi-scale Derivatives</td>
<td>70d</td>
<td><strong>0.659</strong> ± 0.148</td>
</tr>
<tr class="even">
<td>4</td>
<td>Multi-scale + Texture</td>
<td>84d</td>
<td><strong>0.658</strong> ± 0.127</td>
</tr>
<tr class="odd">
<td>5</td>
<td>ResNet-50 (Geometry)</td>
<td>2048d</td>
<td><strong>0.647</strong> ± 0.192</td>
</tr>
<tr class="even">
<td>17</td>
<td>Betti Curves</td>
<td>100d</td>
<td><strong>0.561</strong> ± 0.118</td>
</tr>
</tbody>
</table>

<img data-src="../../../outputs/presentation_visuals/random_vs_spatial_comparison.png" style="width:100.0%" class="r-stretch quarto-figure-center"><p class="caption">Random vs Spatial Comparison</p><aside class="notes">
<p>All methods drop approximately 7 F1 points due to spatial autocorrelation effect. Hybrid approaches combining TDA and Traditional still lead. Deep learning doesn’t outperform traditional methods. TDA alone performs worst.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-these-numbers-mean" class="slide level2">
<h2>What These Numbers Mean</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Real-World Translation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1 = 0.663 (Hybrid)</td>
<td>Best</td>
<td><strong>66% of 30k tiles correct</strong>; 10k need review</td>
</tr>
<tr class="even">
<td>F1 = 0.561 (TDA alone)</td>
<td>Poor</td>
<td><strong>56% accuracy</strong>, unacceptable for operations</td>
</tr>
<tr class="odd">
<td>Δ = 0.10 F1</td>
<td>Improvement</td>
<td><strong>~3,000 fewer errors</strong> vs TDA alone</td>
</tr>
<tr class="even">
<td>10× speedup</td>
<td>Efficiency</td>
<td><strong>100 km² in 2 hrs</strong> vs 20 hrs</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Takeaway</strong></p>
</div>
<div class="callout-content">
<p>Hybrid gives 66% accuracy at 2× speed. Viable for first-pass automated mapping.</p>
</div>
</div>
</div>
<aside class="notes">
<p>The hybrid approach requires expert review for 34% of ambiguous tiles. This is a practical workflow for large-scale mapping operations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="classification-challenges" class="slide level2">
<h2>Classification Challenges</h2>
<p><strong>Hardest classes:</strong></p>
<ul>
<li>Rare classes (Qp, Qe)</li>
<li>Multi-label tiles (Qal + Qc)</li>
</ul>
<p><strong>Where TDA alone fails:</strong></p>
<ul>
<li>Flat valleys (Qal/Alluvium)</li>
<li>Low-relief areas (Qr vs Qc)</li>
</ul>
<aside class="notes">
<p>Rare classes underperform due to limited training data. Multi-label tiles show higher error rates. TDA alone fails in flat valleys with no topological features to capture, and in low-relief areas where TDA cannot distinguish between similar geologies like Qr versus Qc.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="geographic-insights" class="slide level2">
<h2>Geographic Insights</h2>
<p>Models struggle most where geology boundaries are ambiguous.</p>
<aside class="notes">
<p>Models struggle most where geology boundaries are ambiguous or where surficial deposits overlap. This is precisely where expert interpretation is most valuable.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="evidence-tiers-statistical-confidence-levels" class="slide level2">
<h2>Evidence Tiers: Statistical Confidence Levels</h2>

<img data-src="../../../outputs/presentation_visuals/evidence_tier_visualization.png" style="width:90.0%" class="r-stretch quarto-figure-center"><p class="caption">Evidence Tiers</p><ul>
<li><strong>Tier 1 (Ultra-robust):</strong> 3 methods</li>
<li><strong>Tier 2 (Robust):</strong> 12 methods</li>
<li><strong>Tier 3 (Standard):</strong> 5 methods</li>
<li><strong>Tier 4 (Exploratory):</strong> 6 methods</li>
<li><strong>Tier 5 (Not equivalent):</strong> 9 methods</li>
</ul>
<aside class="notes">
<p>Five-tier hierarchy based on TOST equivalence tests and Bonferroni correction. Tier 1 has 3 methods with Bonferroni correction in both CV types (near-certainty). Tier 2 has 12 methods with Bonferroni correction in one CV type. Tier 3 has 5 methods with standard equivalence at alpha equals 0.05 in both CV types. Tier 4 has 6 methods with standard equivalence in one CV type. Tier 5 has 9 methods showing clear differences. This hierarchy accommodates different perspectives on statistical rigor, from ultra-conservative Bonferroni to exploratory single CV type.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="computational-efficiency" class="title-slide slide level1 center">
<h1>Computational Efficiency</h1>

</section>
<section id="timing-comparison-tda-is-10-faster" class="slide level2">
<h2>Timing Comparison: TDA is 10× Faster</h2>

<img data-src="../../../outputs/presentation_visuals/timing_comparison_enhanced.png" style="width:90.0%" class="r-stretch quarto-figure-center"><p class="caption">Computational Cost</p><ul>
<li>TDA: <strong>~0.085 seconds per tile</strong></li>
<li>Traditional: <strong>~0.981 seconds per tile</strong></li>
<li><strong>10× speedup</strong></li>
</ul>
<aside class="notes">
<p>TDA features compute in approximately 0.085 seconds per tile versus traditional methods at 0.981 seconds per tile. TDA is approximately 10 times faster than WhiteboxTools-based traditional features. Deep learning GPU inference is fast at around 0.1 seconds but requires pre-trained models and GPU resources.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="dimensionality-performance-trade-off" class="title-slide slide level1 center">
<h1>Dimensionality-Performance Trade-off</h1>

</section>
<section id="feature-dimension-vs-performance" class="slide level2">
<h2>Feature Dimension vs Performance</h2>

<img data-src="../../../outputs/presentation_visuals/performance_vs_dimension_enhanced.png" style="width:90.0%" class="r-stretch quarto-figure-center"><p class="caption">Performance vs Dimension</p><ul>
<li><strong>Best Traditional:</strong> Multi-scale + Texture (84d, F1=0.731)</li>
<li><strong>Best Hybrid:</strong> Multi-scale + Texture + Betti (184d, F1=0.728)</li>
<li><strong>TDA alone:</strong> Betti curves (100d, F1=0.606)</li>
<li><strong>Deep Learning:</strong> ResNet-50 (2048d, F1=0.714)</li>
<li><strong>Persistence Images:</strong> 5000d, F1=0.669</li>
</ul>
<aside class="notes">
<p>Best Traditional method is Multi-scale plus Texture at 84 dimensions with F1 of 0.731. Best Hybrid is Multi-scale plus Texture plus Betti at 184 dimensions with F1 of 0.728. TDA alone with Betti curves is compact at 100 dimensions but insufficient with F1 of 0.606. Deep Learning ResNet-50 has high dimension at 2048 but doesn’t outperform. Persistence Images at 5000 dimensions have too high dimension for marginal gain. TDA adds value with minimal dimensions when combined with traditional features.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="interpretation-what-worked-and-why" class="title-slide slide level1 center">
<h1>Interpretation: What Worked and Why</h1>

</section>
<section id="what-each-approach-captures" class="slide level2">
<h2>What Each Approach Captures</h2>
<p><strong>Traditional:</strong></p>
<ul>
<li>Local geometry</li>
<li>Multi-scale patterns</li>
<li>Texture</li>
</ul>
<p><strong>TDA:</strong></p>
<ul>
<li>Global connectivity</li>
<li>Multi-scale topology</li>
<li>Shape invariance</li>
</ul>
<aside class="notes">
<p>Traditional features capture local geometry including slope steepness, curvature, and topographic position. They also capture multi-scale patterns like TPI at different radii and roughness at various scales, plus texture including surface roughness and spatial autocorrelation. TDA features capture global connectivity like sinkhole networks and drainage patterns, multi-scale topology with features that persist across elevation thresholds, and shape invariance as a coordinate-free representation of terrain structure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-hybrid-works" class="slide level2">
<h2>Why Hybrid Works</h2>
<p><strong>Best combination:</strong> Multi-scale derivatives + Betti curves</p>
<ul>
<li>Traditional provides local context</li>
<li>TDA captures global connectivity</li>
<li>Together: comprehensive terrain representation</li>
</ul>
<aside class="notes">
<p>This confirms that TDA enhances, not replaces, traditional features. The hybrid approach succeeds because TDA and traditional methods capture complementary information: local geometry versus global connectivity. Deep learning learns opaque patterns but doesn’t outperform, likely due to limited training data at 30k tiles, pre-trained models not specialized for terrain, and no clear advantage over interpretable features.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="when-to-use-what" class="title-slide slide level1 center">
<h1>When to Use What?</h1>

</section>
<section id="when-to-use-tda-vs-traditional" class="slide level2">
<h2>When to Use TDA vs Traditional</h2>
<p><strong>Use TDA when:</strong></p>
<ul>
<li>Terrain connectivity matters</li>
<li>Compact, interpretable features needed</li>
<li>Computational efficiency important</li>
<li>Combining with traditional features feasible</li>
</ul>
<p><strong>Use Traditional when:</strong></p>
<ul>
<li>Local geometry most important</li>
<li>Established, well-understood metrics needed</li>
<li>Interpretability critical</li>
<li>WhiteboxTools cost acceptable</li>
</ul>
<aside class="notes">
<p>Use TDA when terrain connectivity matters, such as in karst, caves, and drainage networks. TDA is approximately 10 times faster than traditional methods. Use traditional methods when local geometry is most important, when you need established well-understood metrics, when interpretability is critical, and when WhiteboxTools computational cost is acceptable.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hybrid-approach-what-to-avoid" class="slide level2">
<h2>Hybrid Approach &amp; What to Avoid</h2>
<p><strong>Use Hybrid when:</strong></p>
<ul>
<li>Resources allow combining features</li>
<li>Best possible performance needed</li>
<li>Both local and global patterns matter</li>
</ul>
<p><strong>Avoid:</strong></p>
<ul>
<li>Persistence images alone</li>
<li>TDA alone for karst classification</li>
</ul>
<aside class="notes">
<p>Use Hybrid TDA plus Traditional when resources allow combining features, when you want best possible performance, and when both local and global patterns matter. Avoid persistence images alone due to high dimension and low performance. Avoid TDA alone for karst classification as it provides insufficient information. Deep learning is only recommended if you have large labeled datasets and need end-to-end learning.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="limitations-future-directions" class="title-slide slide level1 center">
<h1>Limitations &amp; Future Directions</h1>

</section>
<section id="current-limitations" class="slide level2">
<h2>Current Limitations</h2>
<ul>
<li>Spatial CV reveals lower performance</li>
<li>Hyperparameter tuning incomplete</li>
<li>Limited to Kentucky karst</li>
<li>Single filtration function tested</li>
</ul>
<aside class="notes">
<p>Spatial CV reveals lower performance. Random CV inflates metrics by approximately 7 F1 points. Hyperparameter tuning for persistence image resolution and Betti curve bins could be optimized. Results are limited to Kentucky karst and may not generalize to other regions. Only elevation and slope filtrations were tested.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="future-directions" class="slide level2">
<h2>Future Directions</h2>
<p><strong>Methodological:</strong></p>
<ul>
<li>Multi-feature filtrations</li>
<li>Spatial stratification refinement</li>
<li>Hyperparameter optimization</li>
</ul>
<p><strong>Alternative TDA methods:</strong></p>
<ul>
<li>Mapper algorithm, Reeb graphs, Morse-Smale complexes</li>
<li>Extended persistence, zigzag persistence, multiparameter persistence</li>
<li>Graph TDA</li>
</ul>
<p><strong>Application expansion:</strong></p>
<ul>
<li>Test on other karst regions</li>
<li>Apply to non-karst terrain types</li>
<li>Integrate with field survey data</li>
</ul>
<aside class="notes">
<p>Methodological improvements include multi-feature filtrations applying TDA to slope, curvature, and TWI rasters, spatial stratification refinement with better region grouping strategies, and hyperparameter optimization with systematic tuning of TDA parameters. Alternative TDA methods include Mapper algorithm, Reeb graphs, Morse-Smale complexes, extended persistence, zigzag persistence, multiparameter persistence, and Graph TDA using clique complexes on terrain networks. Application expansion includes testing on other karst regions beyond Kentucky, applying to non-karst terrain types, and integrating with field survey data for validation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="conclusions-practical-takeaways" class="title-slide slide level1 center">
<h1>Conclusions: Practical Takeaways</h1>

</section>
<section id="key-findings" class="slide level2">
<h2>Key Findings</h2>
<ol type="1">
<li><p>TDA alone underperforms traditional geomorphometry (F1: 0.606 vs 0.731)</p></li>
<li><p>TDA + Traditional = Best (F1: 0.726 random, 0.663 spatial)</p></li>
<li><p>Computational advantage: TDA is <strong>10× faster</strong> (~0.085s vs ~0.981s per tile)</p></li>
<li><p>Deep learning: expensive, opaque, doesn’t outperform (F1: 0.647 spatial vs 0.663 hybrid)</p></li>
<li><p>Recommendation: Use <strong>hybrid TDA + traditional features</strong></p></li>
</ol>
<aside class="notes">
<p>TDA alone underperforms traditional geomorphometry with F1 of 0.606 versus 0.731. TDA plus Traditional equals Best with F1 of 0.726 in random CV and 0.663 in spatial CV for Multi-scale plus Betti, the ultra-robust method with strongest statistical evidence. TDA is 10 times faster than traditional methods at approximately 0.085 seconds versus 0.981 seconds per tile. Deep learning is expensive, opaque, and doesn’t outperform with F1 of 0.647 spatial versus 0.663 hybrid. Recommendation is to use hybrid TDA plus traditional features for karst terrain classification. Hybrid methods provide the best accuracy with computational efficiency. TDA enhances traditional geomorphometry rather than replacing it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="impact" class="slide level2">
<h2>Impact</h2>
<ul>
<li>Proof-of-concept: TDA provides efficient, interpretable features</li>
<li>Practical value: Hybrid approach offers best accuracy with reasonable cost</li>
<li>Geographic generalization: Spatial CV provides honest performance estimates</li>
</ul>
<aside class="notes">
<p>This is a proof-of-concept demonstrating that TDA provides efficient, interpretable features for terrain classification. The hybrid approach offers practical value with best accuracy and reasonable computational cost. Spatial CV provides honest performance estimates for real-world deployment and geographic generalization.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section id="references" class="title-slide slide level1 smaller scrollable">
<h1>References</h1>
<div id="refs" role="list">

</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>